# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, author: str=None, genre: str=None, isbn: str=None, publisher: str=None, title: str=None, year: int=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param author: The author of this Body.  # noqa: E501
        :type author: str
        :param genre: The genre of this Body.  # noqa: E501
        :type genre: str
        :param isbn: The isbn of this Body.  # noqa: E501
        :type isbn: str
        :param publisher: The publisher of this Body.  # noqa: E501
        :type publisher: str
        :param title: The title of this Body.  # noqa: E501
        :type title: str
        :param year: The year of this Body.  # noqa: E501
        :type year: int
        """
        self.swagger_types = {
            'author': str,
            'genre': str,
            'isbn': str,
            'publisher': str,
            'title': str,
            'year': int
        }

        self.attribute_map = {
            'author': 'author',
            'genre': 'genre',
            'isbn': 'isbn',
            'publisher': 'publisher',
            'title': 'title',
            'year': 'year'
        }

        self._author = author
        self._genre = genre
        self._isbn = isbn
        self._publisher = publisher
        self._title = title
        self._year = year

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def author(self) -> str:
        """Gets the author of this Body.


        :return: The author of this Body.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this Body.


        :param author: The author of this Body.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def genre(self) -> str:
        """Gets the genre of this Body.


        :return: The genre of this Body.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this Body.


        :param genre: The genre of this Body.
        :type genre: str
        """

        self._genre = genre

    @property
    def isbn(self) -> str:
        """Gets the isbn of this Body.


        :return: The isbn of this Body.
        :rtype: str
        """
        return self._isbn

    @isbn.setter
    def isbn(self, isbn: str):
        """Sets the isbn of this Body.


        :param isbn: The isbn of this Body.
        :type isbn: str
        """

        self._isbn = isbn

    @property
    def publisher(self) -> str:
        """Gets the publisher of this Body.


        :return: The publisher of this Body.
        :rtype: str
        """
        return self._publisher

    @publisher.setter
    def publisher(self, publisher: str):
        """Sets the publisher of this Body.


        :param publisher: The publisher of this Body.
        :type publisher: str
        """

        self._publisher = publisher

    @property
    def title(self) -> str:
        """Gets the title of this Body.


        :return: The title of this Body.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Body.


        :param title: The title of this Body.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def year(self) -> int:
        """Gets the year of this Body.


        :return: The year of this Body.
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year: int):
        """Sets the year of this Body.


        :param year: The year of this Body.
        :type year: int
        """

        self._year = year
