# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2001_book import InlineResponse2001Book
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, book: InlineResponse2001Book=None, message: str=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param book: The book of this InlineResponse2001.  # noqa: E501
        :type book: InlineResponse2001Book
        :param message: The message of this InlineResponse2001.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'book': InlineResponse2001Book,
            'message': str
        }

        self.attribute_map = {
            'book': 'book',
            'message': 'message'
        }

        self._book = book
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def book(self) -> InlineResponse2001Book:
        """Gets the book of this InlineResponse2001.


        :return: The book of this InlineResponse2001.
        :rtype: InlineResponse2001Book
        """
        return self._book

    @book.setter
    def book(self, book: InlineResponse2001Book):
        """Sets the book of this InlineResponse2001.


        :param book: The book of this InlineResponse2001.
        :type book: InlineResponse2001Book
        """

        self._book = book

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse2001.


        :return: The message of this InlineResponse2001.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse2001.


        :param message: The message of this InlineResponse2001.
        :type message: str
        """

        self._message = message
