# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse201(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, author: str=None, available: bool=None, genre: str=None, id: int=None, isbn: str=None, publisher: str=None, title: str=None, year: int=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger

        :param author: The author of this InlineResponse201.  # noqa: E501
        :type author: str
        :param available: The available of this InlineResponse201.  # noqa: E501
        :type available: bool
        :param genre: The genre of this InlineResponse201.  # noqa: E501
        :type genre: str
        :param id: The id of this InlineResponse201.  # noqa: E501
        :type id: int
        :param isbn: The isbn of this InlineResponse201.  # noqa: E501
        :type isbn: str
        :param publisher: The publisher of this InlineResponse201.  # noqa: E501
        :type publisher: str
        :param title: The title of this InlineResponse201.  # noqa: E501
        :type title: str
        :param year: The year of this InlineResponse201.  # noqa: E501
        :type year: int
        """
        self.swagger_types = {
            'author': str,
            'available': bool,
            'genre': str,
            'id': int,
            'isbn': str,
            'publisher': str,
            'title': str,
            'year': int
        }

        self.attribute_map = {
            'author': 'author',
            'available': 'available',
            'genre': 'genre',
            'id': 'id',
            'isbn': 'isbn',
            'publisher': 'publisher',
            'title': 'title',
            'year': 'year'
        }

        self._author = author
        self._available = available
        self._genre = genre
        self._id = id
        self._isbn = isbn
        self._publisher = publisher
        self._title = title
        self._year = year

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201
        """
        return util.deserialize_model(dikt, cls)

    @property
    def author(self) -> str:
        """Gets the author of this InlineResponse201.


        :return: The author of this InlineResponse201.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this InlineResponse201.


        :param author: The author of this InlineResponse201.
        :type author: str
        """

        self._author = author

    @property
    def available(self) -> bool:
        """Gets the available of this InlineResponse201.


        :return: The available of this InlineResponse201.
        :rtype: bool
        """
        return self._available

    @available.setter
    def available(self, available: bool):
        """Sets the available of this InlineResponse201.


        :param available: The available of this InlineResponse201.
        :type available: bool
        """

        self._available = available

    @property
    def genre(self) -> str:
        """Gets the genre of this InlineResponse201.


        :return: The genre of this InlineResponse201.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this InlineResponse201.


        :param genre: The genre of this InlineResponse201.
        :type genre: str
        """

        self._genre = genre

    @property
    def id(self) -> int:
        """Gets the id of this InlineResponse201.


        :return: The id of this InlineResponse201.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InlineResponse201.


        :param id: The id of this InlineResponse201.
        :type id: int
        """

        self._id = id

    @property
    def isbn(self) -> str:
        """Gets the isbn of this InlineResponse201.


        :return: The isbn of this InlineResponse201.
        :rtype: str
        """
        return self._isbn

    @isbn.setter
    def isbn(self, isbn: str):
        """Sets the isbn of this InlineResponse201.


        :param isbn: The isbn of this InlineResponse201.
        :type isbn: str
        """

        self._isbn = isbn

    @property
    def publisher(self) -> str:
        """Gets the publisher of this InlineResponse201.


        :return: The publisher of this InlineResponse201.
        :rtype: str
        """
        return self._publisher

    @publisher.setter
    def publisher(self, publisher: str):
        """Sets the publisher of this InlineResponse201.


        :param publisher: The publisher of this InlineResponse201.
        :type publisher: str
        """

        self._publisher = publisher

    @property
    def title(self) -> str:
        """Gets the title of this InlineResponse201.


        :return: The title of this InlineResponse201.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this InlineResponse201.


        :param title: The title of this InlineResponse201.
        :type title: str
        """

        self._title = title

    @property
    def year(self) -> int:
        """Gets the year of this InlineResponse201.


        :return: The year of this InlineResponse201.
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year: int):
        """Sets the year of this InlineResponse201.


        :param year: The year of this InlineResponse201.
        :type year: int
        """

        self._year = year
